### ISSUE TITLE
Error on too many files

### ISSUE THREAD

**Issue by robbestad** [ebrightfield/shadow-drive-rust-cli#1]
Love this project. Really smooth and great. 

One question: what's the limit for sending files? I think some kind of batching may be necessary.

For instance, I get:
```
FileSystemError(
    Os {
        code: 24,
        kind: Uncategorized,
        message: "Too many open files",
    },
)
Error: FileSystemError(
    Os {
        code: 24,
        kind: Uncategorized,
        message: "Too many open files",
    },
)
````
when trying to upload a folder with 10K+ files (8GB in total)

**Comment by ebrightfield** [comment]
hahaha wow! I've never tried nearly that many files, it seems like the OS is what caused the error (rather than net IO or server-side). Linux has limits for this that you can set with `ulimit` and some flags I forget.

Either way, yeah batching should be easy to do, what do you think like 100 files at a time, maybe? 

This will come in handy for me too, when I upload like 10k SVG files for my music tutorials hahah!

**Comment by robbestad** [comment]
Yeah, if you can try 100 and make that happen then that's 20 times better than what I accomplished with my upload tool 🤩

**Comment by ebrightfield** [comment]
Okay, looks like server-side, the limit is only _five files per request_! Any more than that and I would get the following error:
```
Shadow Drive Server Error 500: "null"
```

Try this branch, https://github.com/ebrightfield/shadow-drive-rust-cli/tree/chunked_file_upload

I was able to successfully upload 101 files with it. Batched into chunks of five! ooof

**Comment by robbestad** [comment]
Aha, I should have said I knew about the 5 file limit, but I had hope that you managed to circumvent it :D It works perfectly though.

**Comment by pbtrung** [comment]
Works well. I am using a small bash script to upload 50 files at a time:
```
#!/bin/bash 
cd "dir_with_millions_of_files"
ls | sort | xargs -n 50 shadow-drive-cli -k "wallet_json" --skip-confirm store-files "storage_account_public_key" "$@"
```
Now I am more worried about the future of Shadow Drive. The NFT holders are dumping this coin like crazy, and if the price is too low, the network cannot develop (e.g., not enough incentive for new storage providers). Then, the project would become stagnant and die after a while.
